### ISSUE TITLE
The "example dataset" can't be dowloaded

### ISSUE THREAD

**Issue by zhazhabiu** [ialzugaray/haste#5]
Hi, I find that the "example dataset" can't be dowloaded.
When I click the 'here' word, there is nothing happened.
Could you please offer a example dataset? Or where could I get that?

**Comment by zhazhabiu** [comment]
> Hi, I find that the "example dataset" can't be dowloaded. When I click the 'here' word, there is nothing happened. Could you please offer a example dataset? Or where could I get that?

**Comment by ialzugaray** [comment]
Hi,
I have just verified the link and it works for me, please make sure your browser configuration can follow the link to a file.  In any case, the example file is Shapes Translation (.txt zip) from the Event Camera dataset: https://rpg.ifi.uzh.ch/davis_data.html

Best,
Ignacio
