### ISSUE TITLE
Does this repo contain code of two paper?

### ISSUE THREAD

**Issue by ColieShen** [ialzugaray/haste#6]
Hi, thanks for sharing the awesome code! I am interested in this repo and I can find haste in it. Does this repo contain the code of  "Asynchronous Multi-Hypothesis Tracking of Features with Event Cameras" ? Where can I find the code?

**Comment by ialzugaray** [comment]
Hi,
You can find the code for 3DV'19 "Asynchronous Multi-Hypothesis Tracking of Features with Event Cameras" represented by the so-called _Correlation_ tracker as per the description:

https://github.com/ialzugaray/haste/blob/955c80acf6256d1d4fead22e6b11b8e351b34f53/README.md?plain=1#L118

**Comment by ColieShen** [comment]
Thank you！
